### ISSUE TITLE
Unable to convert type string to int

### ISSUE THREAD

**Issue by alirizaadiyahsi** [scriban/scriban#524] opened 2023-10-17 20:00 UTC
Here is the scriban template:

```
record["OBX"]["OBX-6"]["OBX-6.1"]
```

`OBX-6.1` value in model is `">60 mL/min/1.73m2"`

I am also getting the same error when the value is null, even if I am using `EnableNullIndexer` and `EnableRelaxedTargetAccess`, and the error is occurred only for this property. Other properties working, even though they are null or empty

I am getting the error :

> <input>(1,7563) : error : Unable to convert type `string` to int

> The input string 'OBX-6.1' was not in a correct format.

>    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at Scriban.TemplateContext.ToInt(SourceSpan span, Object value)
   
The followings are working: `"mmol/L"`,  `"gm/dL"`.

It looks like there are some auto-checks for some special characters?

**Comment by xoofx** [comment] 2023-10-19 19:19
I'm on a business trip so little time to follow my OSS projects these days.

I would suggest you to post a full small program that replicate this problem. We can't see from the issue what is behind these array access and what are the exact types. The error indicates that the type has only an int indexer or is an array and not a dictionary, but can't tell.

**Comment by alirizaadiyahsi** [comment] 2023-10-19 19:54
Hi @xoofx thanks for your attention. The project is a bit complicated. Let me try to explain with some code.

My model is nested `Dictionary<sting, object>`

C# Code:

````csharp
public async Task<string> RenderAsync<TRecord>(string templateContent, TRecord record, bool objectItself = false)
{
    var context = new TemplateContext();
    if (objectItself)
    {
        _scriptObject.Import(record);
    }
    else
    {
        _scriptObject.Import(new {Record = record});
    }

    context.PushGlobal(_scriptObject);
    context.EnableNullIndexer = true;
    context.EnableRelaxedTargetAccess = true;
    context.EnableRelaxedFunctionAccess = true;
    context.EnableRelaxedIndexerAccess = true;
    context.EnableRelaxedMemberAccess = true;

    var template = Template.Parse(templateContent);
    return await template.RenderAsync(context);
}
````

Scriban Template:

````
{{ for item0 in record["RESPONSE"]["ORDER_OBSERVATION"] }}
	{{ for item1 in item0["OBSERVATION"] }}
		{{ item1["OBX"]["OBX-6"]["OBX-6.1"] }}
	{{ end }}
{{ end }}
````

Here is the record that is working.

![image](https://github.com/scriban/scriban/assets/4375000/143e6579-899a-46bb-b131-00bb20dce5fb)

And here is the record that is not working. Because ` item1["OBX"]["OBX-6"]` is not an object it looks like it is a string at runtime. So it is giving error for this:  ` item1["OBX"]["OBX-6"]["OBX-6.1"]`. But what about following options:

````csharp
    context.EnableNullIndexer = true;
    context.EnableRelaxedTargetAccess = true;
    context.EnableRelaxedFunctionAccess = true;
    context.EnableRelaxedIndexerAccess = true;
    context.EnableRelaxedMemberAccess = true;
````

![image](https://github.com/scriban/scriban/assets/4375000/1bb0cb04-bc3b-408d-9117-da9cab82d1c1)

**Comment by xoofx** [comment] 2023-10-19 20:44
> And here is the record that is not working. Because ` item1["OBX"]["OBX-6"]` is not an object it looks like it is a string at runtime. So it is giving error for this: ` item1["OBX"]["OBX-6"]["OBX-6.1"]`. But what about following options:

This part is confusing. Do you mean that by changing the configuration on the TemplateContext it is changing your model?

I don't believe this is a problem in Scriban but an interference happening on the model on your side. 

Scriban doesn't change a model when inspecting it, so if your model has a string behind for its value and you are expecting a dictionary, then there is something in your code that triggered the change. 

A repro without a loop with 3 nested dictionary can be done in a few lines. If you report such a case that I can reproduce, then it is a Scriban issue, otherwise, I can only tell that there is something wrong somewhere else in your code, but it is impossible to investigate this from such description, so I will have to close this issue.

**Comment by alirizaadiyahsi** [comment] 2023-10-19 21:33
Sorry, the first comment in this ticket is a bit misleading about the problem.

Here is the summary:

The problem in my dictionary is that some of the properties have `["OBX-6.1"]` and some of them do not.

So the first 3 has the `["OBX-6.1"]`

`["RESPONSE"]["ORDER_OBSERVATION"][0]["OBSERVATION"][0]["OBX"]["OBX-6"]["OBX-6.1"] = "gm/dL"`

But the 4th one has no `["OBX-6.1"]`

`["RESPONSE"]["ORDER_OBSERVATION"][0]["OBSERVATION"][3]["OBX"]["OBX-6"] = ""`

It is like; consider `x` is an array and I am trying to access for example `x[n].y.z` but some `x[n].y` is null in `x` array. So I want null, if there is no `x[n].y.z` instead of getting an exception. Is this possible?

**Comment by xoofx** [comment] 2023-10-21 08:57
> But the 4th one has no ["OBX-6.1"]
> ["RESPONSE"]["ORDER_OBSERVATION"][0]["OBSERVATION"][3]["OBX"]["OBX-6"] = ""
> It is like; consider x is an array and I am trying to access for example x[n].y.z but some x[n].y is null in x array. **So I want null**, if there is no x[n].y.z instead of getting an exception. Is this possible?

Thankks for the clarification. That's precisely the problem then, because your case contracdicts with the what you explain after. The value of `["OBX-6"]` is an empt string, not `null`. You want null but there is a string. 

Closing as it is not a problem in Scriban but in your model.

**Closed by xoofx** 2023-10-21 08:57 UTC
Labels: invalid

**Comment by alirizaadiyahsi** [comment] 2023-10-21 17:04
Yes, the problem was with my model. I fixed that.

The following error message misled me to try to find a solution in a different place :)

> (1,7563) : error : Unable to convert type string to int
> 
> The input string 'OBX-6.1' was not in a correct format.

Thanks for your patience.
